apiVersion: v1
kind: Service
metadata:
  labels:
    app: hypershiftocpvirt
  name: hypershiftocpvirt-apps
  namespace: clusters-hypershiftocpvirt
spec:
  ports:
  - name: https-443
    port: 443
    protocol: TCP
    targetPort: 30983 
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 31972 
  selector:
    kubevirt.io: virt-launcher
  type: LoadBalancer
