apiVersion: v1
data:
  password: cm9vdDEyMw==
  username: cm9vdA==
kind: Secret
metadata:
  labels:
    environment.metal3.io: baremetal
  name: bmc-hcpbmworker
  namespace: clusters-hcpbaremetal
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: hcpbmworker1.intel.demolab.com
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: hcpbaremetal
  name: hcpbmworker1
  namespace: clusters-hcpbaremetal
spec:
  automatedCleaningMode: disabled
  bmc:
    address: 192.168.50.106
    credentialsName: bmc-hcpbmworker
    disableCertificateVerification: true
  bootMACAddress: a4:bf:01:3d:d4:87
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: hcpbmworker2.intel.demolab.com
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: hcpbaremetal
  name: hcpbmworker2
  namespace: clusters-hcpbaremetal
spec:
  automatedCleaningMode: disabled
  bmc:
    address: 192.168.50.115
    credentialsName: bmc-hcpbmworker
    disableCertificateVerification: true
  bootMACAddress: a4:bf:01:38:e8:34
  online: true
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  labels:
    agent-install.openshift.io/bmh: hcpbmworker1
    infraenvs.agent-install.openshift.io: hcpbaremetal
  name: hcpbaremetal-hcpbmworker1
  namespace: clusters-hcpbaremetal
spec:
  config:
    dns-resolver:
      config:
        search:
        - intel.demolab.com
        server:
        - 192.168.40.117
    interfaces:
    - ipv4:
        address:
        - ip: 192.168.40.106
          prefix-length: 24
        enabled: true
      name: eno1
      state: up
      type: ethernet
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.40.2
        next-hop-interface: eno1
        table-id: 254
  interfaces:
  - macAddress: a4:bf:01:3d:d4:86
    name: eno1
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  labels:
    agent-install.openshift.io/bmh: hcpbmworker2
    infraenvs.agent-install.openshift.io: hcpbaremetal
  name: hcpbaremetal-hcpbmworker2
  namespace: clusters-hcpbaremetal
spec:
  config:
    dns-resolver:
      config:
        search:
        - intel.demolab.com
        server:
        - 192.168.40.117
    interfaces:
    - ipv4:
        address:
        - ip: 192.168.40.115
          prefix-length: 24
        enabled: true
      name: eno1
      state: up
      type: ethernet
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.40.2
        next-hop-interface: eno1
        table-id: 254
  interfaces:
  - macAddress: a4:bf:01:38:e8:33
    name: eno1
