apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  labels:
    agent-install.openshift.io/bmh: hcpbmworker1
    infraenvs.agent-install.openshift.io: hcpbaremetal
  name: hcpbaremetal-nmstate
  namespace: clusters-hcpbaremetal
spec:
  config:
    dns-resolver:
      config:
        search:
        - intel.demolab.com
        server:
        - 192.168.40.117
    interfaces:
    - ipv4:
        address:
        - ip: 192.168.40.106
          prefix-length: 24
        enabled: true
      name: eno1
      state: up
      type: ethernet
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.40.2
        next-hop-interface: eno1
        table-id: 254
  interfaces:
  - macAddress: a4:bf:01:3d:d4:86
    name: eno1
